metadata:
  favicon: ''
  title: Import from Git
  description: null
  breakpoints: []
  rendererCachingEnabled: false
  skipDepsComparisonInCompilerCache: false
appSettings:
  properties:
    defaultData: '{}'
  actions:
    appLoad:
      - action: '17201761938370.08688372589059701'
        paramCode: ''
        blockPageLoad: true
        preventDefault: false
        index: 0
    appData: []
  gridVersion: 2
  density: default
internalType: project
