{{ui.slct_acYear.reset()}}
{{ui.slct_term.reset()}}
{{ui.inp_YearlyTheme.reset()}}
{{ui.inp_TermlyTheme.reset()}}
{{ui.inp_SafeguardingTheme.reset()}}
{{ui.inp_psheTheme.reset()}}
{{ui.inp_fbvTheme.reset()}}
{{ui.slct_phase_CommunityReady.reset()}}
{{ui.slct_phase_OvercomingBarriers.reset()}}
{{ui.slct_phase_21stCenturySkills.reset()}}
{{ui.inp_drivequest.reset()}}
